name: .NET Build

on:
  push:
    branches:
      - main
    paths:
      - 'DOTNET/**' # Run the workflow when changes are pushed to files within the vertex_backend directory
  pull_request:
    branches:
      - main
    paths:
      - 'DOTNET/**' # Run the workflow when changes are made in pull requests targeting files within the vertex_backend directory

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: 'vertex_backend' # Checkout the repository in the vertex_backend directory
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Check pwd
        run: pwd
      - name: Restore dependencies
        working-directory: DOTNET # Set the working directory to vertex_backend
        run: dotnet restore
      - name: Build
        working-directory: DOTNET # Set the working directory to vertex_backend
        run: dotnet build --no-restore
