name: .NET Build

on:
  push:
    paths:
      - 'DOTNET/**'
  pull_request:
    paths:
      - 'DOTNET/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x' # Adjust the version as needed

      - name: Build and test
        working-directory: DOTNET
        run: |
          dotnet restore
          dotnet build
          dotnet test
