name: .NET Build

on:
  push:
    branches:
      - main
    paths:
      - 'DOTNET/**' # Run the workflow when changes are pushed to files within the DOTNET directory
  pull_request:
    branches:
      - main
    paths:
      - 'DOTNET/**' # Run the workflow when changes are made in pull requests targeting files within the DOTNET directory

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: 'DOTNET' # Checkout the repository in the DOTNET directory
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Check pwd
        run: pwd
      - name: Check list files/folders
        working-directory: DOTNET
        run: ls -la && pwd
      - name: Restore dependencies
        run: ls && cd DOTNET && ls && dotnet restore
      - name: Build
        working-directory: DOTNET
        run: dotnet build --no-restore
